before:
  hooks:
    - go mod tidy

release:
  target_commitish: "{{ .Commit }}"

builds:
  - main: ./cmd/airmail
    binary: airmail
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - name_template: "airmail_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - LICENSE*
      - CHANGELOG*
      - README*

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      # Exclude changes re. the development environment
      - "^[dD]ev:"
