before:
  hooks:
    - go mod tidy

gomod:
  gobinary: go
  mod: mod

release:
  target_commitish: "{{ .Commit }}"

builds:
  - main: ./cmd/airmail
    binary: airmail
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/hedge10/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/hedge10/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/hedge10/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/hedge10/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date  }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}-arm64v8"
  - name_template: "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}"
    image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{.Tag}}-arm64v8"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      # Exclude changes re. the development environment
      - "^[dD]ev:"
