version: '3.7'

services:
  airmail:
    container_name: airmail
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1025:1025"
      - "8025:8025"
      - "8081:8081"
    volumes:
      - ./:/app
    environment:
      - AM_ENV=dev
      - AM_DEBUG=false
      - AM_SMTP_HOST=localhost
      - AM_SMTP_PORT=1025
      - AM_SMTP_AUTH_MECHANISM=none

