services:
  airmail:
    container_name: airmail
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1025:1025"
      - "8025:8025"
      - "9900:9900"
    volumes:
      - ./:/app
    environment:
      - AM_ENV=dev
      - AM_DEBUG=false
      - AM_SMTP_HOST=${AM_SMTP_HOST}
      - AM_SMTP_PORT=${AM_SMTP_PORT}
      - AM_SMTP_USER=${AM_SMTP_USER}
      - AM_SMTP_PASS=${AM_SMTP_PASS}
      - AM_SMTP_AUTH_MECHANISM=${AM_SMTP_AUTH_MECHANISM}
