version: '3.7'

services:
  airmail:
    container_name: airmail
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1025:1025"
      - "8025:8025"
      - "8081:8081"
    volumes:
      - ./:/app
    environment:
      - AM_ENV=dev
      - AM_DEBUG=false
      - AM_SMTP_HOST=localhost
      - AM_SMTP_PORT=1025
      - AM_SMTP_AUTH_MECHANISM=none
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/