openapi: "3.1.0"
info:
  title: "Airmail API"
  description: |
    Use this API for sending emails to a specified SMTP server.
  version: "1.0"
paths:
  /send:
    post:
      summary: "Sending an email."
      description: "Send an email based on a given JSON input."
      operationId: SendMail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Email'
      responses:
        '200':
          description: Email sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Email'
        '500':
          description: Error sending an email
          content:
            application/json:

schemas:
    Email:
      description: New email request.
      required:
        - from
        - to
        - subject
        - message
      properties:
        from:
          type: object
          description: The sender of the email.
          properties:
            name:
              type: string
            address:
              type: string
        to:
          type: array
          description: A list of email receipients.
          items:
            type: object
            properties:
              name:
                type: string
              address:
                type: string
        cc:
          type: array
          description: A list of CC receipients.
          items:
            type: object
            properties:
              name:
                type: string
              address:
                type: string
        bcc:
          type: array
          description: A list of BCC receipients.
          items:
            type: object
            properties:
              name:
                type: string
              address:
                type: string
        subject:
          type: string
          description: The subject of the email.
        message:
          type: string
          description: The content of the email.
