name: Publish Docker image
on:
  push:
    tags:
      - '*.*.*'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set AIRMAIL_VERSION env
        run: echo "AIRMAIL_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/hedge10/airmail

      - name: Login to GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hedge10
          password: ${{ secrets.RELEASE_PAT }}

      - name: Push to GH Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          registry: ghcr.io
          push: true
          build-args: |
            VERSION=${{ env.AIRMAIL_VERSION }}
          tags: ${{ steps.docker_meta.outputs.tags }}