name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0.5
          mongodb-username: root
          mongodb-password: root
          mongodb-db: airmail

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run tests
        run: go test ./...

      - run: git tag ${{ github.event.inputs.tag }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
