name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New tag name"
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare TLS
        run: /bin/sh ${GITHUB_WORKSPACE}/docker/tls.sh ${GITHUB_WORKSPACE}/docker/openssl.cnf

      - name: Start Mailpit
        uses: addnab/docker-run-action@v3
        with:
          image: axllent/mailpit
          options: -p 1025:1025 -p 8025:8025 -v ${{ github.workspace }}/certs:/airmail-certs -d
          run: |
            /mailpit --smtp-tls-cert /airmail-certs/airmail.pem --smtp-tls-key /airmail-certs/privkey.pem --smtp-auth-accept-any

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.RELEASE_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56

      - name: Run tests
        run: go test ./...

      - run: git tag ${{ github.event.inputs.tag }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          REGISTRY: "ghcr.io"
          IMAGE_NAME: "hedge10/airmail"
