name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.21.x]

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Prepare TLS
        run: |
          chmod +x ${GITHUB_WORKSPACE}/docker/tls.sh
          /bin/sh ${GITHUB_WORKSPACE}/docker/tls.sh ${GITHUB_WORKSPACE}/docker/openssl.cnf

      - name: Start Mailpit
        uses: addnab/docker-run-action@v3
        with:
          image: axllent/mailpit
          options: -p 1025:1025 -p 8025:8025 -v ${{ github.workspace }}/certs:/airmail-certs -d
          run: |
            /mailpit --smtp-tls-cert /airmail-certs/airmail.pem --smtp-tls-key /airmail-certs/privkey.pem --smtp-auth-accept-any

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Test
        run: go test -cover -coverprofile=coverage.out ./...
